'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4959
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<System.Data.Linq.Mapping.DatabaseAttribute(Name:="SuperCases")>  _
Partial Public Class DaoSuperCases
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
    Partial Private Sub Insertfacvecab(instance As DataDaoSuperCases.facvecab)
    End Sub
    Partial Private Sub Updatefacvecab(instance As DataDaoSuperCases.facvecab)
    End Sub
    Partial Private Sub Deletefacvecab(instance As DataDaoSuperCases.facvecab)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.Alertas.My.MySettings.Default.SuperCasesConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property facvecabs() As System.Data.Linq.Table(Of DataDaoSuperCases.facvecab)
		Get
			Return Me.GetTable(Of DataDaoSuperCases.facvecab)
		End Get
	End Property
End Class

Namespace DataDaoSuperCases
	
	<Table(Name:="dbo.facvecab")>  _
	Partial Public Class facvecab
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _fac_codigo As Integer
		
		Private _fac_tipcom As String
		
		Private _fac_tipmov As String
		
		Private _fac_fecha As Date
		
		Private _fac_tipo As Char
		
		Private _fac_ptovta As Integer
		
		Private _fac_numero As Integer
		
		Private _cli_codigo As Integer
		
		Private _fac_descue As Decimal
		
		Private _fac_neto1 As Decimal
		
		Private _fac_neto2 As Decimal
		
		Private _fac_iva1 As Decimal
		
		Private _fac_iva2 As Decimal
		
		Private _fac_poriv1 As Decimal
		
		Private _fac_poriv2 As Decimal
		
		Private _fac_periva As Decimal
		
		Private _fac_perib As Decimal
		
		Private _fac_total As Decimal
		
		Private _fac_anulad As Boolean
		
		Private _cli_nombre As String
		
		Private _cli_cuit As String
		
		Private _iva_codigo As Integer
		
		Private _pro_codigo As Integer
		
		Private _cli_locali As String
		
		Private _cli_codpos As String
		
		Private _cli_domici As String
		
		Private _fac_cai As String
		
		Private _fac_caiven As System.Nullable(Of Date)
		
		Private _fac_hojas As Integer
		
		Private _asi_codigo As Integer
		
		Private _fac_forpag As Integer
		
		Private _fac_cuoimp As Decimal
		
		Private _fac_cuocan As Byte
		
		Private _fac_dolar As Decimal
		
		Private _fac_moneda As Char
		
		Private _usu_fecacc As Date
		
		Private _usu_codigo As Integer
		
		Private _pco_codigo As Short
		
		Private _fac_impint As Decimal
		
		Private _dep_codigo As Integer
		
		Private _fac_flete As Decimal
		
		Private _fac_recargo As Decimal
		
		Private _fac_descue1 As Decimal
		
		Private _fac_descue2 As Decimal
		
		Private _fac_fecven As System.Nullable(Of Date)
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub Onfac_codigoChanging(value As Integer)
    End Sub
    Partial Private Sub Onfac_codigoChanged()
    End Sub
    Partial Private Sub Onfac_tipcomChanging(value As String)
    End Sub
    Partial Private Sub Onfac_tipcomChanged()
    End Sub
    Partial Private Sub Onfac_tipmovChanging(value As String)
    End Sub
    Partial Private Sub Onfac_tipmovChanged()
    End Sub
    Partial Private Sub Onfac_fechaChanging(value As Date)
    End Sub
    Partial Private Sub Onfac_fechaChanged()
    End Sub
    Partial Private Sub Onfac_tipoChanging(value As Char)
    End Sub
    Partial Private Sub Onfac_tipoChanged()
    End Sub
    Partial Private Sub Onfac_ptovtaChanging(value As Integer)
    End Sub
    Partial Private Sub Onfac_ptovtaChanged()
    End Sub
    Partial Private Sub Onfac_numeroChanging(value As Integer)
    End Sub
    Partial Private Sub Onfac_numeroChanged()
    End Sub
    Partial Private Sub Oncli_codigoChanging(value As Integer)
    End Sub
    Partial Private Sub Oncli_codigoChanged()
    End Sub
    Partial Private Sub Onfac_descueChanging(value As Decimal)
    End Sub
    Partial Private Sub Onfac_descueChanged()
    End Sub
    Partial Private Sub Onfac_neto1Changing(value As Decimal)
    End Sub
    Partial Private Sub Onfac_neto1Changed()
    End Sub
    Partial Private Sub Onfac_neto2Changing(value As Decimal)
    End Sub
    Partial Private Sub Onfac_neto2Changed()
    End Sub
    Partial Private Sub Onfac_iva1Changing(value As Decimal)
    End Sub
    Partial Private Sub Onfac_iva1Changed()
    End Sub
    Partial Private Sub Onfac_iva2Changing(value As Decimal)
    End Sub
    Partial Private Sub Onfac_iva2Changed()
    End Sub
    Partial Private Sub Onfac_poriv1Changing(value As Decimal)
    End Sub
    Partial Private Sub Onfac_poriv1Changed()
    End Sub
    Partial Private Sub Onfac_poriv2Changing(value As Decimal)
    End Sub
    Partial Private Sub Onfac_poriv2Changed()
    End Sub
    Partial Private Sub Onfac_perivaChanging(value As Decimal)
    End Sub
    Partial Private Sub Onfac_perivaChanged()
    End Sub
    Partial Private Sub Onfac_peribChanging(value As Decimal)
    End Sub
    Partial Private Sub Onfac_peribChanged()
    End Sub
    Partial Private Sub Onfac_totalChanging(value As Decimal)
    End Sub
    Partial Private Sub Onfac_totalChanged()
    End Sub
    Partial Private Sub Onfac_anuladChanging(value As Boolean)
    End Sub
    Partial Private Sub Onfac_anuladChanged()
    End Sub
    Partial Private Sub Oncli_nombreChanging(value As String)
    End Sub
    Partial Private Sub Oncli_nombreChanged()
    End Sub
    Partial Private Sub Oncli_cuitChanging(value As String)
    End Sub
    Partial Private Sub Oncli_cuitChanged()
    End Sub
    Partial Private Sub Oniva_codigoChanging(value As Integer)
    End Sub
    Partial Private Sub Oniva_codigoChanged()
    End Sub
    Partial Private Sub Onpro_codigoChanging(value As Integer)
    End Sub
    Partial Private Sub Onpro_codigoChanged()
    End Sub
    Partial Private Sub Oncli_localiChanging(value As String)
    End Sub
    Partial Private Sub Oncli_localiChanged()
    End Sub
    Partial Private Sub Oncli_codposChanging(value As String)
    End Sub
    Partial Private Sub Oncli_codposChanged()
    End Sub
    Partial Private Sub Oncli_domiciChanging(value As String)
    End Sub
    Partial Private Sub Oncli_domiciChanged()
    End Sub
    Partial Private Sub Onfac_caiChanging(value As String)
    End Sub
    Partial Private Sub Onfac_caiChanged()
    End Sub
    Partial Private Sub Onfac_caivenChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub Onfac_caivenChanged()
    End Sub
    Partial Private Sub Onfac_hojasChanging(value As Integer)
    End Sub
    Partial Private Sub Onfac_hojasChanged()
    End Sub
    Partial Private Sub Onasi_codigoChanging(value As Integer)
    End Sub
    Partial Private Sub Onasi_codigoChanged()
    End Sub
    Partial Private Sub Onfac_forpagChanging(value As Integer)
    End Sub
    Partial Private Sub Onfac_forpagChanged()
    End Sub
    Partial Private Sub Onfac_cuoimpChanging(value As Decimal)
    End Sub
    Partial Private Sub Onfac_cuoimpChanged()
    End Sub
    Partial Private Sub Onfac_cuocanChanging(value As Byte)
    End Sub
    Partial Private Sub Onfac_cuocanChanged()
    End Sub
    Partial Private Sub Onfac_dolarChanging(value As Decimal)
    End Sub
    Partial Private Sub Onfac_dolarChanged()
    End Sub
    Partial Private Sub Onfac_monedaChanging(value As Char)
    End Sub
    Partial Private Sub Onfac_monedaChanged()
    End Sub
    Partial Private Sub Onusu_fecaccChanging(value As Date)
    End Sub
    Partial Private Sub Onusu_fecaccChanged()
    End Sub
    Partial Private Sub Onusu_codigoChanging(value As Integer)
    End Sub
    Partial Private Sub Onusu_codigoChanged()
    End Sub
    Partial Private Sub Onpco_codigoChanging(value As Short)
    End Sub
    Partial Private Sub Onpco_codigoChanged()
    End Sub
    Partial Private Sub Onfac_impintChanging(value As Decimal)
    End Sub
    Partial Private Sub Onfac_impintChanged()
    End Sub
    Partial Private Sub Ondep_codigoChanging(value As Integer)
    End Sub
    Partial Private Sub Ondep_codigoChanged()
    End Sub
    Partial Private Sub Onfac_fleteChanging(value As Decimal)
    End Sub
    Partial Private Sub Onfac_fleteChanged()
    End Sub
    Partial Private Sub Onfac_recargoChanging(value As Decimal)
    End Sub
    Partial Private Sub Onfac_recargoChanged()
    End Sub
    Partial Private Sub Onfac_descue1Changing(value As Decimal)
    End Sub
    Partial Private Sub Onfac_descue1Changed()
    End Sub
    Partial Private Sub Onfac_descue2Changing(value As Decimal)
    End Sub
    Partial Private Sub Onfac_descue2Changed()
    End Sub
    Partial Private Sub Onfac_fecvenChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub Onfac_fecvenChanged()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			OnCreated
		End Sub
		
		<Column(Storage:="_fac_codigo", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
		Public Property fac_codigo() As Integer
			Get
				Return Me._fac_codigo
			End Get
			Set
				If ((Me._fac_codigo = value)  _
							= false) Then
					Me.Onfac_codigoChanging(value)
					Me.SendPropertyChanging
					Me._fac_codigo = value
					Me.SendPropertyChanged("fac_codigo")
					Me.Onfac_codigoChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_tipcom", DbType:="Char(2) NOT NULL", CanBeNull:=false)>  _
		Public Property fac_tipcom() As String
			Get
				Return Me._fac_tipcom
			End Get
			Set
				If (String.Equals(Me._fac_tipcom, value) = false) Then
					Me.Onfac_tipcomChanging(value)
					Me.SendPropertyChanging
					Me._fac_tipcom = value
					Me.SendPropertyChanged("fac_tipcom")
					Me.Onfac_tipcomChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_tipmov", DbType:="Char(2) NOT NULL", CanBeNull:=false)>  _
		Public Property fac_tipmov() As String
			Get
				Return Me._fac_tipmov
			End Get
			Set
				If (String.Equals(Me._fac_tipmov, value) = false) Then
					Me.Onfac_tipmovChanging(value)
					Me.SendPropertyChanging
					Me._fac_tipmov = value
					Me.SendPropertyChanged("fac_tipmov")
					Me.Onfac_tipmovChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_fecha", DbType:="DateTime NOT NULL")>  _
		Public Property fac_fecha() As Date
			Get
				Return Me._fac_fecha
			End Get
			Set
				If ((Me._fac_fecha = value)  _
							= false) Then
					Me.Onfac_fechaChanging(value)
					Me.SendPropertyChanging
					Me._fac_fecha = value
					Me.SendPropertyChanged("fac_fecha")
					Me.Onfac_fechaChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_tipo", DbType:="Char(1) NOT NULL")>  _
		Public Property fac_tipo() As Char
			Get
				Return Me._fac_tipo
			End Get
			Set
				If ((Me._fac_tipo = value)  _
							= false) Then
					Me.Onfac_tipoChanging(value)
					Me.SendPropertyChanging
					Me._fac_tipo = value
					Me.SendPropertyChanged("fac_tipo")
					Me.Onfac_tipoChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_ptovta", DbType:="Int NOT NULL")>  _
		Public Property fac_ptovta() As Integer
			Get
				Return Me._fac_ptovta
			End Get
			Set
				If ((Me._fac_ptovta = value)  _
							= false) Then
					Me.Onfac_ptovtaChanging(value)
					Me.SendPropertyChanging
					Me._fac_ptovta = value
					Me.SendPropertyChanged("fac_ptovta")
					Me.Onfac_ptovtaChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_numero", DbType:="Int NOT NULL")>  _
		Public Property fac_numero() As Integer
			Get
				Return Me._fac_numero
			End Get
			Set
				If ((Me._fac_numero = value)  _
							= false) Then
					Me.Onfac_numeroChanging(value)
					Me.SendPropertyChanging
					Me._fac_numero = value
					Me.SendPropertyChanged("fac_numero")
					Me.Onfac_numeroChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_cli_codigo", DbType:="Int NOT NULL")>  _
		Public Property cli_codigo() As Integer
			Get
				Return Me._cli_codigo
			End Get
			Set
				If ((Me._cli_codigo = value)  _
							= false) Then
					Me.Oncli_codigoChanging(value)
					Me.SendPropertyChanging
					Me._cli_codigo = value
					Me.SendPropertyChanged("cli_codigo")
					Me.Oncli_codigoChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_descue", DbType:="Decimal(12,2) NOT NULL")>  _
		Public Property fac_descue() As Decimal
			Get
				Return Me._fac_descue
			End Get
			Set
				If ((Me._fac_descue = value)  _
							= false) Then
					Me.Onfac_descueChanging(value)
					Me.SendPropertyChanging
					Me._fac_descue = value
					Me.SendPropertyChanged("fac_descue")
					Me.Onfac_descueChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_neto1", DbType:="Decimal(12,2) NOT NULL")>  _
		Public Property fac_neto1() As Decimal
			Get
				Return Me._fac_neto1
			End Get
			Set
				If ((Me._fac_neto1 = value)  _
							= false) Then
					Me.Onfac_neto1Changing(value)
					Me.SendPropertyChanging
					Me._fac_neto1 = value
					Me.SendPropertyChanged("fac_neto1")
					Me.Onfac_neto1Changed
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_neto2", DbType:="Decimal(12,2) NOT NULL")>  _
		Public Property fac_neto2() As Decimal
			Get
				Return Me._fac_neto2
			End Get
			Set
				If ((Me._fac_neto2 = value)  _
							= false) Then
					Me.Onfac_neto2Changing(value)
					Me.SendPropertyChanging
					Me._fac_neto2 = value
					Me.SendPropertyChanged("fac_neto2")
					Me.Onfac_neto2Changed
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_iva1", DbType:="Decimal(12,2) NOT NULL")>  _
		Public Property fac_iva1() As Decimal
			Get
				Return Me._fac_iva1
			End Get
			Set
				If ((Me._fac_iva1 = value)  _
							= false) Then
					Me.Onfac_iva1Changing(value)
					Me.SendPropertyChanging
					Me._fac_iva1 = value
					Me.SendPropertyChanged("fac_iva1")
					Me.Onfac_iva1Changed
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_iva2", DbType:="Decimal(12,2) NOT NULL")>  _
		Public Property fac_iva2() As Decimal
			Get
				Return Me._fac_iva2
			End Get
			Set
				If ((Me._fac_iva2 = value)  _
							= false) Then
					Me.Onfac_iva2Changing(value)
					Me.SendPropertyChanging
					Me._fac_iva2 = value
					Me.SendPropertyChanged("fac_iva2")
					Me.Onfac_iva2Changed
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_poriv1", DbType:="Decimal(5,2) NOT NULL")>  _
		Public Property fac_poriv1() As Decimal
			Get
				Return Me._fac_poriv1
			End Get
			Set
				If ((Me._fac_poriv1 = value)  _
							= false) Then
					Me.Onfac_poriv1Changing(value)
					Me.SendPropertyChanging
					Me._fac_poriv1 = value
					Me.SendPropertyChanged("fac_poriv1")
					Me.Onfac_poriv1Changed
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_poriv2", DbType:="Decimal(5,2) NOT NULL")>  _
		Public Property fac_poriv2() As Decimal
			Get
				Return Me._fac_poriv2
			End Get
			Set
				If ((Me._fac_poriv2 = value)  _
							= false) Then
					Me.Onfac_poriv2Changing(value)
					Me.SendPropertyChanging
					Me._fac_poriv2 = value
					Me.SendPropertyChanged("fac_poriv2")
					Me.Onfac_poriv2Changed
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_periva", DbType:="Decimal(12,2) NOT NULL")>  _
		Public Property fac_periva() As Decimal
			Get
				Return Me._fac_periva
			End Get
			Set
				If ((Me._fac_periva = value)  _
							= false) Then
					Me.Onfac_perivaChanging(value)
					Me.SendPropertyChanging
					Me._fac_periva = value
					Me.SendPropertyChanged("fac_periva")
					Me.Onfac_perivaChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_perib", DbType:="Decimal(12,2) NOT NULL")>  _
		Public Property fac_perib() As Decimal
			Get
				Return Me._fac_perib
			End Get
			Set
				If ((Me._fac_perib = value)  _
							= false) Then
					Me.Onfac_peribChanging(value)
					Me.SendPropertyChanging
					Me._fac_perib = value
					Me.SendPropertyChanged("fac_perib")
					Me.Onfac_peribChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_total", DbType:="Decimal(12,2) NOT NULL")>  _
		Public Property fac_total() As Decimal
			Get
				Return Me._fac_total
			End Get
			Set
				If ((Me._fac_total = value)  _
							= false) Then
					Me.Onfac_totalChanging(value)
					Me.SendPropertyChanging
					Me._fac_total = value
					Me.SendPropertyChanged("fac_total")
					Me.Onfac_totalChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_anulad", DbType:="Bit NOT NULL")>  _
		Public Property fac_anulad() As Boolean
			Get
				Return Me._fac_anulad
			End Get
			Set
				If ((Me._fac_anulad = value)  _
							= false) Then
					Me.Onfac_anuladChanging(value)
					Me.SendPropertyChanging
					Me._fac_anulad = value
					Me.SendPropertyChanged("fac_anulad")
					Me.Onfac_anuladChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_cli_nombre", DbType:="Char(50) NOT NULL", CanBeNull:=false)>  _
		Public Property cli_nombre() As String
			Get
				Return Me._cli_nombre
			End Get
			Set
				If (String.Equals(Me._cli_nombre, value) = false) Then
					Me.Oncli_nombreChanging(value)
					Me.SendPropertyChanging
					Me._cli_nombre = value
					Me.SendPropertyChanged("cli_nombre")
					Me.Oncli_nombreChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_cli_cuit", DbType:="Char(13) NOT NULL", CanBeNull:=false)>  _
		Public Property cli_cuit() As String
			Get
				Return Me._cli_cuit
			End Get
			Set
				If (String.Equals(Me._cli_cuit, value) = false) Then
					Me.Oncli_cuitChanging(value)
					Me.SendPropertyChanging
					Me._cli_cuit = value
					Me.SendPropertyChanged("cli_cuit")
					Me.Oncli_cuitChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_iva_codigo", DbType:="Int NOT NULL")>  _
		Public Property iva_codigo() As Integer
			Get
				Return Me._iva_codigo
			End Get
			Set
				If ((Me._iva_codigo = value)  _
							= false) Then
					Me.Oniva_codigoChanging(value)
					Me.SendPropertyChanging
					Me._iva_codigo = value
					Me.SendPropertyChanged("iva_codigo")
					Me.Oniva_codigoChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_pro_codigo", DbType:="Int NOT NULL")>  _
		Public Property pro_codigo() As Integer
			Get
				Return Me._pro_codigo
			End Get
			Set
				If ((Me._pro_codigo = value)  _
							= false) Then
					Me.Onpro_codigoChanging(value)
					Me.SendPropertyChanging
					Me._pro_codigo = value
					Me.SendPropertyChanged("pro_codigo")
					Me.Onpro_codigoChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_cli_locali", DbType:="Char(50) NOT NULL", CanBeNull:=false)>  _
		Public Property cli_locali() As String
			Get
				Return Me._cli_locali
			End Get
			Set
				If (String.Equals(Me._cli_locali, value) = false) Then
					Me.Oncli_localiChanging(value)
					Me.SendPropertyChanging
					Me._cli_locali = value
					Me.SendPropertyChanged("cli_locali")
					Me.Oncli_localiChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_cli_codpos", DbType:="Char(8) NOT NULL", CanBeNull:=false)>  _
		Public Property cli_codpos() As String
			Get
				Return Me._cli_codpos
			End Get
			Set
				If (String.Equals(Me._cli_codpos, value) = false) Then
					Me.Oncli_codposChanging(value)
					Me.SendPropertyChanging
					Me._cli_codpos = value
					Me.SendPropertyChanged("cli_codpos")
					Me.Oncli_codposChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_cli_domici", DbType:="Char(50) NOT NULL", CanBeNull:=false)>  _
		Public Property cli_domici() As String
			Get
				Return Me._cli_domici
			End Get
			Set
				If (String.Equals(Me._cli_domici, value) = false) Then
					Me.Oncli_domiciChanging(value)
					Me.SendPropertyChanging
					Me._cli_domici = value
					Me.SendPropertyChanged("cli_domici")
					Me.Oncli_domiciChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_cai", DbType:="Char(14) NOT NULL", CanBeNull:=false)>  _
		Public Property fac_cai() As String
			Get
				Return Me._fac_cai
			End Get
			Set
				If (String.Equals(Me._fac_cai, value) = false) Then
					Me.Onfac_caiChanging(value)
					Me.SendPropertyChanging
					Me._fac_cai = value
					Me.SendPropertyChanged("fac_cai")
					Me.Onfac_caiChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_caiven", DbType:="DateTime")>  _
		Public Property fac_caiven() As System.Nullable(Of Date)
			Get
				Return Me._fac_caiven
			End Get
			Set
				If (Me._fac_caiven.Equals(value) = false) Then
					Me.Onfac_caivenChanging(value)
					Me.SendPropertyChanging
					Me._fac_caiven = value
					Me.SendPropertyChanged("fac_caiven")
					Me.Onfac_caivenChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_hojas", DbType:="Int NOT NULL")>  _
		Public Property fac_hojas() As Integer
			Get
				Return Me._fac_hojas
			End Get
			Set
				If ((Me._fac_hojas = value)  _
							= false) Then
					Me.Onfac_hojasChanging(value)
					Me.SendPropertyChanging
					Me._fac_hojas = value
					Me.SendPropertyChanged("fac_hojas")
					Me.Onfac_hojasChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_asi_codigo", DbType:="Int NOT NULL")>  _
		Public Property asi_codigo() As Integer
			Get
				Return Me._asi_codigo
			End Get
			Set
				If ((Me._asi_codigo = value)  _
							= false) Then
					Me.Onasi_codigoChanging(value)
					Me.SendPropertyChanging
					Me._asi_codigo = value
					Me.SendPropertyChanged("asi_codigo")
					Me.Onasi_codigoChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_forpag", DbType:="Int NOT NULL")>  _
		Public Property fac_forpag() As Integer
			Get
				Return Me._fac_forpag
			End Get
			Set
				If ((Me._fac_forpag = value)  _
							= false) Then
					Me.Onfac_forpagChanging(value)
					Me.SendPropertyChanging
					Me._fac_forpag = value
					Me.SendPropertyChanged("fac_forpag")
					Me.Onfac_forpagChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_cuoimp", DbType:="Decimal(12,2) NOT NULL")>  _
		Public Property fac_cuoimp() As Decimal
			Get
				Return Me._fac_cuoimp
			End Get
			Set
				If ((Me._fac_cuoimp = value)  _
							= false) Then
					Me.Onfac_cuoimpChanging(value)
					Me.SendPropertyChanging
					Me._fac_cuoimp = value
					Me.SendPropertyChanged("fac_cuoimp")
					Me.Onfac_cuoimpChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_cuocan", DbType:="TinyInt NOT NULL")>  _
		Public Property fac_cuocan() As Byte
			Get
				Return Me._fac_cuocan
			End Get
			Set
				If ((Me._fac_cuocan = value)  _
							= false) Then
					Me.Onfac_cuocanChanging(value)
					Me.SendPropertyChanging
					Me._fac_cuocan = value
					Me.SendPropertyChanged("fac_cuocan")
					Me.Onfac_cuocanChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_dolar", DbType:="Decimal(8,3) NOT NULL")>  _
		Public Property fac_dolar() As Decimal
			Get
				Return Me._fac_dolar
			End Get
			Set
				If ((Me._fac_dolar = value)  _
							= false) Then
					Me.Onfac_dolarChanging(value)
					Me.SendPropertyChanging
					Me._fac_dolar = value
					Me.SendPropertyChanged("fac_dolar")
					Me.Onfac_dolarChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_moneda", DbType:="Char(1) NOT NULL")>  _
		Public Property fac_moneda() As Char
			Get
				Return Me._fac_moneda
			End Get
			Set
				If ((Me._fac_moneda = value)  _
							= false) Then
					Me.Onfac_monedaChanging(value)
					Me.SendPropertyChanging
					Me._fac_moneda = value
					Me.SendPropertyChanged("fac_moneda")
					Me.Onfac_monedaChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_usu_fecacc", DbType:="DateTime NOT NULL")>  _
		Public Property usu_fecacc() As Date
			Get
				Return Me._usu_fecacc
			End Get
			Set
				If ((Me._usu_fecacc = value)  _
							= false) Then
					Me.Onusu_fecaccChanging(value)
					Me.SendPropertyChanging
					Me._usu_fecacc = value
					Me.SendPropertyChanged("usu_fecacc")
					Me.Onusu_fecaccChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_usu_codigo", DbType:="Int NOT NULL")>  _
		Public Property usu_codigo() As Integer
			Get
				Return Me._usu_codigo
			End Get
			Set
				If ((Me._usu_codigo = value)  _
							= false) Then
					Me.Onusu_codigoChanging(value)
					Me.SendPropertyChanging
					Me._usu_codigo = value
					Me.SendPropertyChanged("usu_codigo")
					Me.Onusu_codigoChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_pco_codigo", DbType:="SmallInt NOT NULL")>  _
		Public Property pco_codigo() As Short
			Get
				Return Me._pco_codigo
			End Get
			Set
				If ((Me._pco_codigo = value)  _
							= false) Then
					Me.Onpco_codigoChanging(value)
					Me.SendPropertyChanging
					Me._pco_codigo = value
					Me.SendPropertyChanged("pco_codigo")
					Me.Onpco_codigoChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_impint", DbType:="Decimal(9,2) NOT NULL")>  _
		Public Property fac_impint() As Decimal
			Get
				Return Me._fac_impint
			End Get
			Set
				If ((Me._fac_impint = value)  _
							= false) Then
					Me.Onfac_impintChanging(value)
					Me.SendPropertyChanging
					Me._fac_impint = value
					Me.SendPropertyChanged("fac_impint")
					Me.Onfac_impintChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_dep_codigo", DbType:="Int NOT NULL")>  _
		Public Property dep_codigo() As Integer
			Get
				Return Me._dep_codigo
			End Get
			Set
				If ((Me._dep_codigo = value)  _
							= false) Then
					Me.Ondep_codigoChanging(value)
					Me.SendPropertyChanging
					Me._dep_codigo = value
					Me.SendPropertyChanged("dep_codigo")
					Me.Ondep_codigoChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_flete", DbType:="Decimal(12,2) NOT NULL")>  _
		Public Property fac_flete() As Decimal
			Get
				Return Me._fac_flete
			End Get
			Set
				If ((Me._fac_flete = value)  _
							= false) Then
					Me.Onfac_fleteChanging(value)
					Me.SendPropertyChanging
					Me._fac_flete = value
					Me.SendPropertyChanged("fac_flete")
					Me.Onfac_fleteChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_recargo", DbType:="Decimal(12,2) NOT NULL")>  _
		Public Property fac_recargo() As Decimal
			Get
				Return Me._fac_recargo
			End Get
			Set
				If ((Me._fac_recargo = value)  _
							= false) Then
					Me.Onfac_recargoChanging(value)
					Me.SendPropertyChanging
					Me._fac_recargo = value
					Me.SendPropertyChanged("fac_recargo")
					Me.Onfac_recargoChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_descue1", DbType:="Decimal(12,2) NOT NULL")>  _
		Public Property fac_descue1() As Decimal
			Get
				Return Me._fac_descue1
			End Get
			Set
				If ((Me._fac_descue1 = value)  _
							= false) Then
					Me.Onfac_descue1Changing(value)
					Me.SendPropertyChanging
					Me._fac_descue1 = value
					Me.SendPropertyChanged("fac_descue1")
					Me.Onfac_descue1Changed
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_descue2", DbType:="Decimal(12,2) NOT NULL")>  _
		Public Property fac_descue2() As Decimal
			Get
				Return Me._fac_descue2
			End Get
			Set
				If ((Me._fac_descue2 = value)  _
							= false) Then
					Me.Onfac_descue2Changing(value)
					Me.SendPropertyChanging
					Me._fac_descue2 = value
					Me.SendPropertyChanged("fac_descue2")
					Me.Onfac_descue2Changed
				End If
			End Set
		End Property
		
		<Column(Storage:="_fac_fecven", DbType:="SmallDateTime")>  _
		Public Property fac_fecven() As System.Nullable(Of Date)
			Get
				Return Me._fac_fecven
			End Get
			Set
				If (Me._fac_fecven.Equals(value) = false) Then
					Me.Onfac_fecvenChanging(value)
					Me.SendPropertyChanging
					Me._fac_fecven = value
					Me.SendPropertyChanged("fac_fecven")
					Me.Onfac_fecvenChanged
				End If
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
	End Class
End Namespace
